identity:    Jeremy Neander
title:       Jeremy Neander
baseurl:     /
url:         http://jneander.com
copyright:   Jeremy Neander 2016
email:       jeremy.neander@gmail.com

description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

highlighter: true
markdown:    kramdown

source:      "./jekyll"
destination: "./build"
include:     ["_pages"]
sections:    ["writing", "resume"]

permalink:   "/writing/:title/"
excerpt_separator: ""

gems:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
